# Form implementation generated from reading ui file 'c:\Users\Asus\Documents\Tesis\Proyecto_PyQt6\ui\Test_v2.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(802, 501)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: white;\n"
"\n"
"\n"
"\n"
"")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.test_name = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_name.sizePolicy().hasHeightForWidth())
        self.test_name.setSizePolicy(sizePolicy)
        self.test_name.setMinimumSize(QtCore.QSize(180, 0))
        self.test_name.setObjectName("test_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.test_name)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.add_inst_btn = QtWidgets.QPushButton(self.widget)
        self.add_inst_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_inst_btn.sizePolicy().hasHeightForWidth())
        self.add_inst_btn.setSizePolicy(sizePolicy)
        self.add_inst_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.add_inst_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_inst_btn.setStyleSheet("#add_inst_btn {\n"
"border: none;\n"
"padding:  10px;\n"
"background-color: #3f5c73;\n"
"color: white;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"#add_inst_btn::hover{\n"
"background-color: #517da6\n"
"}")
        self.add_inst_btn.setObjectName("add_inst_btn")
        self.verticalLayout.addWidget(self.add_inst_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.run_test_btn = QtWidgets.QPushButton(self.widget)
        self.run_test_btn.setEnabled(False)
        self.run_test_btn.setStyleSheet("#run_test_btn {\n"
"border: 1px solid #3f5c73;\n"
"background-color: #3f5c73;\n"
"color: white;\n"
"font-weight: bold;\n"
"padding: 5px 15px;\n"
"}\n"
"\n"
"#run_test_btn::hover{\n"
"background-color: #517da6\n"
"}\n"
"\n"
"#run_test_btn::disabled {\n"
"background-color: grey;\n"
"}")
        self.run_test_btn.setObjectName("run_test_btn")
        self.horizontalLayout_4.addWidget(self.run_test_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.create_test_btn = QtWidgets.QPushButton(self.widget)
        self.create_test_btn.setStyleSheet("#create_test_btn {\n"
"border: 1px solid #5b8cb9;\n"
"padding: 5px 15px;\n"
"}\n"
"\n"
"#create_test_btn::hover {\n"
"background-color: #f2f5ff;\n"
"}")
        self.create_test_btn.setObjectName("create_test_btn")
        self.horizontalLayout_4.addWidget(self.create_test_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.widget)
        self.cancel_btn.setStyleSheet("#cancel_btn {\n"
"border: 1px solid #5b8cb9;\n"
"padding: 5px 15px;\n"
"}\n"
"\n"
"#cancel_btn::hover {\n"
"background-color: #f2f5ff;\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_4.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.results_btn = QtWidgets.QPushButton(self.widget)
        self.results_btn.setEnabled(False)
        self.results_btn.setObjectName("results_btn")
        self.horizontalLayout_3.addWidget(self.results_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addWidget(self.widget)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background-color:#ebf0f4; border: 1px solid #ddf5ff;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 421, 477))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("background-color: white;\n"
"font: 12pt \"Segoe UI\";\n"
"color: #5b8cb9;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.scroll_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.scroll_widget.setAutoFillBackground(False)
        self.scroll_widget.setStyleSheet("border: none")
        self.scroll_widget.setObjectName("scroll_widget")
        self.verticalLayout_3.addWidget(self.scroll_widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; color:#5b8cb9;\">Create Test</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "Test Name:"))
        self.label_5.setText(_translate("Dialog", "Number of nodes:"))
        self.label_6.setText(_translate("Dialog", "Concurrency number:"))
        self.add_inst_btn.setText(_translate("Dialog", "Add Instruction"))
        self.run_test_btn.setText(_translate("Dialog", "Run"))
        self.create_test_btn.setText(_translate("Dialog", "Create"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.results_btn.setText(_translate("Dialog", "Results"))
        self.label_4.setText(_translate("Dialog", "Instructions"))
